language: node_js
node_js:
  - "8"
  
dist: trusty
sudo: required
branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - npm run deploy
  - cp dist/hunterjobweb/index.html dist/hunterjobweb/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/hunterjobweb
  on:
    branch: master