language: node_js
node_js:
- '8'
sudo: true

before_script:
  - npm install -g @angular/cli

script:
- ng build --prod --aot --base-href https://gollesobhe.github.io/hunterJobWeb/

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  local_dir: dist/hunterjobweb
  on:
    branch: master