language: node_js
node_js:
- '8'
sudo: true
script:
- npm run deploy
branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g

script:
  - npm build --base-href /hunterJobWeb/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  local_dir: dist/hunterjobweb
  on:
    branch: master